server:
  port: ${SERVER_PORT:8080}

spring:
  ai:
    mcp:
      server:
        name: kaiten-mcp
        instructions: >
          Набор инструментов для работы с Kaiten: поиск карточек, чтение
        type: SYNC
        sse-endpoint: /mcp/sse
        sse-message-endpoint: /mcp/message
        stdio: false

logging:
  level:
    io.modelcontextprotocol: DEBUG

kaiten:
  api-url: ${KAITEN_API_URL:}
  api-token: ${KAITEN_API_TOKEN:}

security:
  bearer-token: ${MCP_BEARER_TOKEN:}
